improve

diff --git a/usr/sbin/configure-dynamic-resolution b/usr/sbin/configure-dynamic-resolution
--- a/usr/sbin/configure-dynamic-resolution
+++ b/usr/sbin/configure-dynamic-resolution
@@ -89,7 +89,7 @@ set_bool_opt() {
     return 1
   fi
   write_config_value "${config_option_id}" "${bool_opt}"
-  log notice "Saved: ${config_option_id} = ${bool_opt}"
+  log info "Saved: ${config_option_id} = ${bool_opt}"
   printf '%s\n' ""
   return 0
 }
@@ -109,14 +109,47 @@ set_resolution_opt() {
   ## TOML requires strings to be quoted, thus we wrap the resolution opt in
   ## escaped quotes.
   write_config_value "${config_option_id}" "\"${resolution_opt}\""
-  log notice "Saved: ${config_option_id} = ${resolution_opt}"
+  log info "Saved: ${config_option_id} = ${resolution_opt}"
   printf '%s\n' ""
   return 0
 }
 
+announce_change() {
+  local config_option_id normalized_value
+
+  config_option_id="${1:-}"
+  normalized_value="${2:-}"
+
+  case "${config_option_id}" in
+    'enable_dynamic_resolution')
+      if [ "${normalized_value}" = "true" ]; then
+        log notice "Dynamic resolution has been turned ON."
+      else
+        log notice "Dynamic resolution has been turned OFF."
+      fi
+      ;;
+    'warn_on_dynamic_resolution_refuse')
+      if [ "${normalized_value}" = "true" ]; then
+        log notice "Warning messages have been turned ON."
+      else
+        log notice "Warning messages have been turned OFF."
+      fi
+      ;;
+    'standard_default_resolution')
+      log notice "The normal default resolution has been set to ${normalized_value}."
+      ;;
+    'small_default_resolution')
+      log notice "The small default resolution has been set to ${normalized_value}."
+      ;;
+    *)
+      log notice "Settings have been updated."
+      ;;
+  esac
+}
+
 configure_dynamic_resolution() {
   local config_option_list config_option_id_list config_option \
-    config_option_id config_option_idx selected_idx opt_arg bool_opt resolution_opt did_change
+    config_option_id config_option_idx selected_idx opt_arg bool_opt resolution_opt did_change normalized_value
 
   as_root
 
@@ -193,9 +226,16 @@ configure_dynamic_resolution() {
           read -r bool_opt
           bool_opt="${bool_opt:-y}"
         fi
-        if ! set_bool_opt "${config_option_id}" "${bool_opt}"; then
+        normalized_value="$(validate_bool_opt "${bool_opt}")"
+        if [ -z "${normalized_value}" ]; then
+          log error "Option '${bool_opt}' is invalid. Please use: yes/no, true/false, on/off, or 1/0."
+          printf '%s\n' ""
           continue
         fi
+        if ! set_bool_opt "${config_option_id}" "${normalized_value}"; then
+          continue
+        fi
+        announce_change "${config_option_id}" "${normalized_value}"
         did_change=true
         ;;
 
@@ -207,9 +247,16 @@ configure_dynamic_resolution() {
           read -r bool_opt
           bool_opt="${bool_opt:-n}"
         fi
-        if ! set_bool_opt "${config_option_id}" "${bool_opt}"; then
+        normalized_value="$(validate_bool_opt "${bool_opt}")"
+        if [ -z "${normalized_value}" ]; then
+          log error "Option '${bool_opt}' is invalid. Please use: yes/no, true/false, on/off, or 1/0."
+          printf '%s\n' ""
           continue
         fi
+        if ! set_bool_opt "${config_option_id}" "${normalized_value}"; then
+          continue
+        fi
+        announce_change "${config_option_id}" "${normalized_value}"
         did_change=true
         ;;
 
@@ -221,9 +268,16 @@ configure_dynamic_resolution() {
           read -r resolution_opt
           resolution_opt="${resolution_opt:-$default_resolution}"
         fi
-        if ! set_resolution_opt "${config_option_id}" "${resolution_opt}"; then
+        normalized_value="$(validate_resolution_opt "${resolution_opt}")"
+        if [ -z "${normalized_value}" ]; then
+          log error "'${resolution_opt}' does not look like a screen resolution. Please use something like 1920x1080."
+          printf '%s\n' ""
           continue
         fi
+        if ! set_resolution_opt "${config_option_id}" "${normalized_value}"; then
+          continue
+        fi
+        announce_change "${config_option_id}" "${normalized_value}"
         did_change=true
         ;;
 
@@ -235,9 +289,16 @@ configure_dynamic_resolution() {
           read -r resolution_opt
           resolution_opt="${resolution_opt:-$default_resolution}"
         fi
-        if ! set_resolution_opt "${config_option_id}" "${resolution_opt}"; then
+        normalized_value="$(validate_resolution_opt "${resolution_opt}")"
+        if [ -z "${normalized_value}" ]; then
+          log error "'${resolution_opt}' does not look like a screen resolution. Please use something like 1920x1080."
+          printf '%s\n' ""
           continue
         fi
+        if ! set_resolution_opt "${config_option_id}" "${normalized_value}"; then
+          continue
+        fi
+        announce_change "${config_option_id}" "${normalized_value}"
         did_change=true
         ;;
 
