vbox-guest-installer: add root check

diff --git a/usr/bin/vbox-guest-installer b/usr/bin/vbox-guest-installer
--- a/usr/bin/vbox-guest-installer
+++ b/usr/bin/vbox-guest-installer
@@ -11,6 +11,12 @@ virtualbox_guest_additions_packages_still_installed() {
    exit 0
 }
 
+if [ "$(id -u)" != "0" ]; then
+   echo "ERROR: Must run as root. Run:"
+   echo "sudo $0"
+   exit 112
+fi
+
 if dpkg-query --show "virtualbox-guest-x11" &>/dev/null ; then
    virtualbox_guest_additions_packages_still_installed
 fi
