vbox-guest-installer: set correct kernel version inside chroot

diff --git a/usr/bin/vbox-guest-installer b/usr/bin/vbox-guest-installer
--- a/usr/bin/vbox-guest-installer
+++ b/usr/bin/vbox-guest-installer
@@ -23,6 +23,52 @@ virtualbox_guest_additions_packages_still_installed() {
    exit 0
 }
 
+## {{{ taken from https://github.com/dell/dkms/blob/master/dkms_common.postinst
+
+## GPLv2
+
+# Copyright (C) 2002-2005 Flavio Stanchina
+# Copyright (C) 2005-2006 Aric Cyr
+# Copyright (C) 2007 Mario Limonciello
+# Copyright (C) 2009 Alberto Milone
+
+# Get the most recent kernel on Debian based systems. This keeps
+# into account both the version and the ABI. If the current kernel
+# is the most recent kernel then the function will print a null string.
+_get_newest_kernel_debian() {
+    NEWEST_KERNEL=
+    NEWEST_VERSION=
+    NEWEST_ABI=
+
+    for kernel in /boot/config-*; do
+        [ -f "$kernel" ] || continue
+        KERNEL=${kernel#*-}
+        KERNEL_VERSION=${KERNEL%%-*}
+        ABI=${KERNEL#*-}
+        ABI=${ABI%%-*}
+
+        if [ -z "$NEWEST_KERNEL" ]; then
+            # The 1st time get a version which is bigger than $1
+            COMPARE_TO=$1
+        else
+            # Get the biggest version
+            COMPARE_TO="$NEWEST_VERSION-$NEWEST_ABI"
+        fi
+
+        # if $kernel is greater than $COMPARE_TO
+        if [ `dpkg --compare-versions "$KERNEL_VERSION-$ABI" ge "$COMPARE_TO" && echo "yes" || \
+              echo "no"` = "yes" ]; then
+            NEWEST_KERNEL=$KERNEL
+            NEWEST_VERSION=$KERNEL_VERSION
+            NEWEST_ABI=$ABI
+        fi
+    done
+
+    echo "$NEWEST_KERNEL"
+}
+
+## }}}
+
 error_handler() {
    $output_command "$0 ERROR: BASH_COMMAND: '$BASH_COMMAND' failed with exit code '$?'." >&2
    $output_command "$0 ERROR: Please search Whonix forums and report if required." >&2
@@ -44,6 +90,32 @@ if [ "$(id -u)" != "0" ]; then
    $output_command "$0 ERROR: Must run as root. Run:"
    $output_command "sudo $0"
    exit 112
+fi
+
+if ischroot --default-false ; then
+   echo "$0 INFO: chroot detected."
+   ## /opt/VBoxGuestAdditions-6.1.18/init/vboxadd uses:
+   # test -z "${TARGET_VER}" && TARGET_VER=`uname -r`
+   #
+   #if test -d /lib/modules/"$TARGET_VER"/build; then
+   #   setup_modules "$TARGET_VER"
+   #   depmod
+   #else
+   #   info "Kernel headers not found for target kernel $TARGET_VER. \
+#Please install them and execute
+#/sbin/rcvboxadd setup"
+   #fi
+   ## Output of `uname -r` is host kernel version.
+   ## Not build chroot kernel version.
+   ## Therefore building for that version would fail.
+   ## Hence, manually setting to correct version.
+   TARGET_VER="$(_get_newest_kernel_debian)"
+   export TARGET_VER
+   echo "$0 INFO: chroot detected. Therefore: export TARGET_VER='$TARGET_VER'"
+   if [ "$TARGET_VER" = "" ]; then
+      echo "$0 ERROR: variable TARGET_VER is empty. Failing closed. Exit error."
+      exit 1
+   fi
 fi
 
 if dpkg-query --show "virtualbox-guest-x11" &>/dev/null ; then
