output

diff --git a/usr/bin/vbox-guest-installer b/usr/bin/vbox-guest-installer
--- a/usr/bin/vbox-guest-installer
+++ b/usr/bin/vbox-guest-installer
@@ -51,9 +51,9 @@ popd >/dev/null
 pushd /var/cache/vm-config-dist/vbox-guest-additions-extracted-makeself >/dev/null
 
 if ./install.sh ; then
-   echo "$0 INFO: Success, vm-config-dist installed VirtualBox guest additions."
+   echo "$0 INFO: Success, vm-config-dist installed VirtualBox guest additions from virtualbox-guest-additions-iso."
 else
-   echo "$0 ERROR: vm-config-dist failed to install VirtualBox guest additions. See:" >&2
+   echo "$0 ERROR: vm-config-dist failed to install VirtualBox guest additions from virtualbox-guest-additions-iso. See:" >&2
    echo "https://www.whonix.org/wiki/ga" >&2
 fi
 
